#include "vm.h"
#include "vm/instruction_set.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void execute_ADD(MeatsVM *vm)
{
	uint8_t reg = fetch(vm);
	uint8_t bytes[sizeof(uint64_t)];
	fetch_bytes(vm, bytes, sizeof(uint64_t));
	uint64_t value = vm_bytes_to_uint64(bytes);
	vm_set_register(vm, reg, vm_get_register(vm, reg) + value);
	// printf("r%u value: %ld \n", reg, vm_get_register(vm,reg));
}

void disasm_ADD(MeatsVM *vm)
{
	uint8_t reg = fetch(vm);
	uint8_t bytes[sizeof(uint64_t)];
	fetch_bytes(vm, bytes, sizeof(uint64_t));
	uint64_t value = vm_bytes_to_uint64(bytes);
	printf("ADD r%u %ld\n", reg, value);
}

uint8_t *bytecode_ADD(uint8_t reg, uint64_t value)
{
	// Static buffer to hold the bytecode (10 bytes: 1 byte for opcode, 1 byte for register, and 8 bytes for the 64-bit value)
	uint8_t *bytecode = malloc(ADD_INSTR_SIZE);
	bytecode[0] = 0xAA; // ADD opcode for 64-bit (or another suitable opcode)
	bytecode[1] = reg;  // Register number

	// Split the 64-bit value into 8 bytes and store them in the bytecode
	bytecode[2] = (value >> 56) & 0xFF; // Most significant byte
	bytecode[3] = (value >> 48) & 0xFF;
	bytecode[4] = (value >> 40) & 0xFF;
	bytecode[5] = (value >> 32) & 0xFF;
	bytecode[6] = (value >> 24) & 0xFF;
	bytecode[7] = (value >> 16) & 0xFF;
	bytecode[8] = (value >> 8) & 0xFF;
	bytecode[9] = value & 0xFF; // Least significant byte

	return bytecode; // Return the generated bytecode
}
