#include "vm.h"
#include "vm/instruction_set.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void execute_MOV(MeatsVM *vm)
{
	uint8_t reg = fetch(vm);
	uint8_t value = fetch(vm);
	vm_set_register(vm, reg, (uint64_t)value);
}

void disasm_MOV(MeatsVM *vm)
{
	uint8_t reg = fetch(vm);
	uint8_t value = fetch(vm);
	printf("MOV r%d %d\n", reg, value);
}

uint8_t *bytecode_MOV(uint8_t reg, uint8_t value)
{
	uint8_t *bytecode = malloc(MOV_INSTR_SIZE);
	if (bytecode == NULL)
		exit(123);
	bytecode[0] = 0xDA;  // MOV opcode
	bytecode[1] = reg;   // Register number
	bytecode[2] = value; // Value

	return bytecode; // Return the generated bytecode
}
