#include "vm.h"
#include "vm/instruction_set.h"
#include <stdio.h>
#include <stdlib.h>

void execute_MOVI(MeatsVM *vm)
{
	uint8_t reg = fetch(vm);
	static uint8_t bytes[sizeof(uint32_t)];
	uint32_t value;
	fetch_bytes(vm, bytes, sizeof(uint32_t));
	value = vm_bytes_to_uint32(bytes);
	vm_set_register(vm, reg, value);
}

void disasm_MOVI(MeatsVM *vm)
{
	uint8_t reg = fetch(vm);
	static uint8_t bytes[sizeof(uint32_t)];
	uint32_t value;
	fetch_bytes(vm, bytes, sizeof(uint32_t));
	value = vm_bytes_to_uint32(bytes);
	printf("MOVI r%d %ld\n", reg, (uint64_t)value);
}

uint8_t *bytecode_MOVI(uint8_t reg, uint32_t value)
{
	// Static buffer to hold the bytecode (6 bytes: 1 byte for opcode, 1 byte for register, 4 bytes for the value)
	static uint8_t bytecode[6];

	bytecode[0] = 0xDB; // MOVI opcode
	bytecode[1] = reg;	// Register number

	// Split the 32-bit value into 4 bytes and store them in the bytecode
	bytecode[2] = (value >> 24) & 0xFF; // Most significant byte
	bytecode[3] = (value >> 16) & 0xFF; // 2nd byte
	bytecode[4] = (value >> 8) & 0xFF;	// 3rd byte
	bytecode[5] = value & 0xFF;			// Least significant byte

	return bytecode; // Return the generated bytecode
}
