#include "vm.h"
#include "vm/instruction_set.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void execute_MOVI(MeatsVM *vm)
{
	uint8_t reg = fetch(vm);
	uint8_t bytes[sizeof(uint32_t)];
	uint32_t value;
	fetch_bytes(vm, bytes, sizeof(uint32_t));
	value = vm_bytes_to_uint32(bytes);
	vm_set_register(vm, reg, value);
}

void disasm_MOVI(MeatsVM *vm)
{
	uint8_t reg = fetch(vm);
	uint8_t bytes[sizeof(uint32_t)];
	uint32_t value;
	fetch_bytes(vm, bytes, sizeof(uint32_t));
	value = vm_bytes_to_uint32(bytes);
	printf("MOVI r%d %ld\n", reg, (uint64_t)value);
}

uint8_t *bytecode_MOVI(uint8_t reg, uint32_t value)
{
	uint8_t *bytecode = malloc(ADD_INSTR_SIZE);
	if (bytecode == NULL)
		exit(123);

	bytecode[0] = 0xDB; // MOVI opcode
	bytecode[1] = reg;  // Register number

	// Split the 64-bit value into 4 bytes and store them in the bytecode
	bytecode[6] = (value >> 24) & 0xFF;
	bytecode[7] = (value >> 16) & 0xFF;
	bytecode[8] = (value >> 8) & 0xFF;
	bytecode[9] = value & 0xFF; // Least significant byte

	return bytecode; // Return the generated bytecode
}
